### ISSUE TITLE
Drift detection fails with invalid memory address on HelmRelease renaming

### ISSUE THREAD

**Issue by bdols** [fluxcd/helm-controller#669]
I've encountered the fallowing panics trying out the helm-controller drift detection, helm-controller:v0.31.1. I was moving an existing helm release to new directory under an active kustomization, at the time:

```
{"level":"error","ts":"2023-04-07T05:58:49.025Z","logger":"runtime","msg":"Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)\ngoroutine 379 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x1d2e980?, 0x32e67a0})\n\tk8s.io/apimachinery@v0.26.2/pkg/util/runtime/runtime.go:75 +0x99\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:111 +0xc5\npanic({0x1d2e980, 0x32e67a0})\n\truntime/panic.go:884 +0x213\ngithub.com/fluxcd/helm-controller/internal/diff.(*Differ).Diff(0x1fe0000?, {0x22e1a90, 0xc00675b800}, 0x0)\n\tgithub.com/fluxcd/helm-controller/internal/diff/differ.go:73 +0x49\ngithub.com/fluxcd/helm-controller/controllers.(*HelmReleaseReconciler).reconcileRelease(_, {_, _}, {{{0x1b439af, 0xb}, {0xc0008eab80, 0x1e}}, {{0xc001e8d4b6, 0xa}, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/fluxcd/helm-controller/controllers/helmrelease_controller.go:343 +0x61c\ngithub.com/fluxcd/helm-controller/controllers.(*HelmReleaseReconciler).reconcile(_, {_, _}, {{{0x1b439af, 0xb}, {0xc0008eab80, 0x1e}}, {{0xc001e8d4b6, 0xa}, {0x0, ...}, ...}, ...})\n\tgithub.com/fluxcd/helm-controller/controllers/helmrelease_controller.go:287 +0xfdb\ngithub.com/fluxcd/helm-controller/controllers.(*HelmReleaseReconciler).Reconcile(0xc0009b11e0, {0x22e1a90, 0xc00675b800}, {{{0xc006696120?, 0x0?}, {0xc006696110?, 0x40e047?}}})\n\tgithub.com/fluxcd/helm-controller/controllers/helmrelease_controller.go:181 +0x550\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x22e1a90?, {0x22e1a90?, 0xc00675b800?}, {{{0xc006696120?, 0x1c3d280?}, {0xc006696110?, 0x0?}}})\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122 +0xc8\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004a75e0, {0x22e19e8, 0xc0000cce60}, {0x1dc2780?, 0xc015dfeb00?})\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323 +0x35f\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004a75e0, {0x22e19e8, 0xc0000cce60})\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274 +0x1d9\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:231 +0x587\n","stacktrace":"k8s.io/apimachinery/pkg/util/runtime.logPanic\n\tk8s.io/apimachinery@v0.26.2/pkg/util/runtime/runtime.go:79\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:111\nruntime.gopanic\n\truntime/panic.go:884\nruntime.panicmem\n\truntime/panic.go:260\nruntime.sigpanic\n\truntime/signal_unix.go:837\ngithub.com/fluxcd/helm-controller/internal/diff.(*Differ).Diff\n\tgithub.com/fluxcd/helm-controller/internal/diff/differ.go:73\ngithub.com/fluxcd/helm-controller/controllers.(*HelmReleaseReconciler).reconcileRelease\n\tgithub.com/fluxcd/helm-controller/controllers/helmrelease_controller.go:343\ngithub.com/fluxcd/helm-controller/controllers.(*HelmReleaseReconciler).reconcile\n\tgithub.com/fluxcd/helm-controller/controllers/helmrelease_controller.go:287\ngithub.com/fluxcd/helm-controller/controllers.(*HelmReleaseReconciler).Reconcile\n\tgithub.com/fluxcd/helm-controller/controllers/helmrelease_controller.go:181\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}

```

and 

```
{"level":"error","ts":"2023-04-07T05:58:49.025Z","msg":"Reconciler error","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"dev-es-api","namespace":"dev-es-api"},"namespace":"dev-es-api","name":"dev-es-api","reconcileID":"63cac592-4545-4b9f-9f9a-efeed4a6080b","error":"panic: runtime error: invalid memory address or nil pointer dereference [recovered]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
```

**Comment by stefanprodan** [comment]
@bdols did the move to a different dir changed the release namespace?

**Comment by bdols** [comment]
it should not have, but I ran `flux diff kustomization` beforehand, and now I see that the releasename is different because of the kustomization namePrefix that I introduced so it deleted the helm release dev-es-api/es-api and is trying to create dev-es-api/dev-es-api now. (I was moving ops-es-api to dev-es-api as a way to promote some changes..):

```% flux diff kustomization apps  --path apps/dev
✓  Kustomization diffing...
► Kafka/dev-es-api/dev-es-api created
► KafkaUser/dev-es-api/dev-es-api created
► KafkaTopic/dev-es-api/dev-message-store-all created
► ConfigMap/dev-es-api/dev-kafka-metrics created
► PrometheusRule/dev-es-api/dev-prometheus-k8s-rules created
► PodMonitor/dev-es-api/dev-cluster-operator-metrics created
► PodMonitor/dev-es-api/dev-entity-operator-metrics created
► PodMonitor/dev-es-api/dev-bridge-metrics created
► PodMonitor/dev-es-api/dev-kafka-resources-metrics created
► HelmRelease/dev-es-api/dev-es-api created
► HelmRelease/dev-es-api/dev-es-api-enqueue created
► HelmRelease/dev-es-api/dev-es-api-elastic-writer created
► Namespace/ops-es-api deleted
► ConfigMap/ops-es-api/kafka-metrics deleted
► HelmRelease/dev-es-api/es-api deleted
► HelmRelease/ops-es-api/es-api deleted
► Kafka/ops-es-api/ops-es-api deleted
► KafkaTopic/ops-es-api/message-store-all deleted
► KafkaUser/ops-es-api/es-api deleted
► PrometheusRule/ops-es-api/prometheus-k8s-rules deleted
⚠️ identified at least one change, exiting with non-zero exit code
```

The helm installs do not appear in the output of  `helm list -a -A`

**Comment by stefanprodan** [comment]
Ok this helps, renaming the HelmRelease means that the old one gets deleted then recreated. Drift detection should be skipped for deleted release to fix the panic.

**Comment by bdols** [comment]
OK, I'll try deleteing the HelmReleases and reconcile the kustomization in the mean time, and then disable drift detection if that doesn't recreate the releases, if you don't need anything more from me

**Comment by stefanprodan** [comment]
You need to disable drift detection for helm-controller to recreate the release, then enable it back.
